### ISSUE TITLE
package it.unifi.cerm.playmorphia does not exist

### ISSUE THREAD

**Issue by amixpal** [morellik/play-morphia#5]
Thanks for upgrading the morphia library but I am unable to compile the project

#Stacktrace
`play.sbt.PlayExceptions$CompilationException: Compilation error[package it.unifi.cerm.playmorphia does not exist]
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
	at play.sbt.PlayExceptions$CompilationException$.apply(PlayExceptions.scala:34)
	at scala.Option.map(Option.scala:146)
	at play.sbt.run.PlayReload$.$anonfun$taskFailureHandler$1(PlayReload.scala:33)
	at scala.Option.map(Option.scala:146)
	at play.sbt.run.PlayReload$.taskFailureHandler(PlayReload.scala:28)
	at play.sbt.run.PlayReload$.compileFailure(PlayReload.scala:24)
	at play.sbt.run.PlayReload$.$anonfun$compile$3(PlayReload.scala:51)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at play.sbt.run.PlayReload$.compile(PlayReload.scala:51)
`

I performed following steps:

1. Make changes in applicaiton.conf as per the tutorial 
2. Added `Playorphia.jar` to the project
3. Created MongoClientFactory 
4. Compile the project and it gave me above error.

This is kind of strange because while importing `it.unifi.cerm.playmorphia.MongoClientFactory` in my mongoClientFactory class it's showing me no errors. I can even import it into another class but at the time of compilation it's throwing me above stacks

What mistake I am making here?

**Comment by morellik** [comment]
Did you copy the jar file in the lib folder of your Play project?

**Comment by amixpal** [comment]
Morellik, Thanks for your response. Everything is working fine. It was an IntelliJ bug (Intellij was not able to import the library at compile time). However, After resolving it; I am getting one more issue in dependency injection:
```

`! @78d2nfnda - Internal server error, for (GET) [/] ->
 
play.api.UnexpectedException: Unexpected exception[CreationException: Unable to create injector, see the following errors:

1) No implementation for play.inject.ApplicationLifecycle was bound.
  while locating play.inject.ApplicationLifecycle
    for the 1st parameter of it.unifi.cerm.playmorphia.PlayMorphia.<init>(PlayMorphia.java:26)
  at it.unifi.cerm.playmorphia.MorphiaModule.bindings(MorphiaModule.java:15):
Binding(class it.unifi.cerm.playmorphia.PlayMorphia to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error]
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1.reload(DevServerStart.scala:186)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1.get(DevServerStart.scala:124)
	at play.core.server.AkkaHttpServer.play$core$server$AkkaHttpServer$$handleRequest(AkkaHttpServer.scala:222)
	at play.core.server.AkkaHttpServer$$anonfun$4.apply(AkkaHttpServer.scala:137)
	at play.core.server.AkkaHttpServer$$anonfun$4.apply(AkkaHttpServer.scala:137)
	at akka.stream.impl.fusing.MapAsync$$anon$25.onPush(Ops.scala:1194)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:519)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:482)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:378)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:585)
Caused by: com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for play.inject.ApplicationLifecycle was bound.
  while locating play.inject.ApplicationLifecycle
    for the 1st parameter of it.unifi.cerm.playmorphia.PlayMorphia.<init>(PlayMorphia.java:26)
  at it.unifi.cerm.playmorphia.MorphiaModule.bindings(MorphiaModule.java:15):
Binding(class it.unifi.cerm.playmorphia.PlayMorphia to self) (via modules: com.google.inject.util.Modules$OverrideModule -> play.api.inject.guice.GuiceableModuleConversions$$anon$1)

1 error
	at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:470)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:155)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:84)
	at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:185)
	at play.api.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.scala:137)
	at play.api.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.scala:21)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$1.apply(DevServerStart.scala:174)
	at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$1.apply(DevServerStart.scala:171)`
```

What is missing here?

**Comment by morellik** [comment]
Which version of Play are you using?

**Comment by amixpal** [comment]
It's   `"com.typesafe.play" %% "play" % "2.6.15"`
where as sbt version is `sbt.version=1.1.6`

**Comment by amixpal** [comment]
It's not even working with 
`"com.typesafe.play" %% "play" % "2.1.0-M1",`

**Comment by morellik** [comment]
Try to use the jar file from the branch branch-2.6

**Comment by amixpal** [comment]
Tried and same error

**Comment by morellik** [comment]
I'll out of  office unti next monday. If you can wait I'll check it in the next week.

**Comment by morellik** [comment]
For the moment you can try to use it on Play 2.5.12

**Comment by amixpal** [comment]
So, I copied your `PlayMorphia` , `MorphiaModule` and `MongoClientFactory` in my porject and provided following configuration in `app.conf`:

`playmorphia {
  uri="mongodb://127.0.0.1:27017/talent"
  database="talent"
  models="models"
}`

In `reference.conf` I have added the module name `play.modules.enabled  += "configuration.MorphiaModule"`

After applying debugger in `MorphiaModule.bindings()` method, I can see the value of `environment` and `configuration` but after that, it gives the error

`No implementation for play.inject.ApplicationLifecycle was bound.
  while locating play.inject.ApplicationLifecycle
    for the 1st parameter of configuration.PlayMorphia.<init>(PlayMorphia.java:25)
  at configuration.MorphiaModule.bindings(MorphiaModule.java:12):`

I am not able to understand because you have already provided the `ApplicaitonLifeCycle` in `PlayMorphia` class. Any idea why It's happening. I will try to debug it

BTW I also tried the above version. It's not working for me 

Is it related to this : https://stackoverflow.com/questions/47330018/play-2-4-dependency-injection-forgets-about-builtin-classes-in-unit-tests-if-mod

**Comment by morellik** [comment]
I tested the morphia under Play 2.6.15 and all works fine. I don't know the reason because it doesn't works for you.

I created a new Play 2.6.15 project named mongotest:
> sbt new playframework/play-java-seed.g8

I put the following lines in build.sbt:
```
libraryDependencies ++= Seq(
    guice,
    "org.mongodb.morphia" % "morphia" % "1.3.2",
    "org.mongodb" % "mongo-java-driver" % "3.7.0"
    )

```
In conf/application.conf I added:
```
playmorphia {
    uri="mongodb://127.0.0.1:27017/mongotest"
    database="mongotest"
    models="models"
}
```
I created a _lib_ folder into my mongotest project and I copied _play-morphia.jar_ into the _lib_ folder.

After that I created _models_ and _repositories_ folder under _app_ directory

After that I created _User.java_ model under _models_ folder:

```
package models;

import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;

@Entity(value = "mongotest.users")
public class User  {

    @Id
    private ObjectId _id;
    private String firstname;
    private String lastname;
    private String email;

    public ObjectId getId() {
        return _id;
    }

    public void setId(ObjectId _id) {
        this._id = _id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}
```

So, I created _UserRepository.java_ file under _repositories_ folder:
```

package repositories;

import it.unifi.cerm.playmorphia.PlayMorphia;
import models.User;
import org.bson.types.ObjectId;

import javax.inject.Inject;

public class UserRepository {


    private final PlayMorphia morphia;

    @Inject
    public UserRepository(PlayMorphia morphia) {
        this.morphia = morphia;
    }

    public User findById(String id) {
        User user = morphia.
                datastore().
                createQuery(User.class).
                field("_id").
                equal(new ObjectId(id)).
                get();
        return user;
    }

    public void save(User u) {
        morphia.datastore().save(u);
    }
}

```

And, I write some code in HomeController.java to write a new user to the db.
```

package controllers;

import models.User;
import play.mvc.*;
import repositories.UserRepository;

import javax.inject.Inject;

/**
 * This controller contains an action to handle HTTP requests
 * to the application's home page.
 */
public class HomeController extends Controller {

    @Inject
    private UserRepository user;
    public Result index() {
        User u = new User();
        u.setFirstname("Paolo");
        u.setLastname("Rossi");
        u.setEmail("rossi@email.com");
        user.save(u);
        return ok(views.html.index.render());
    }
}
```

Running the application, and going to localhost:9000 with my browser, I'm able to see the new user in the db:
```

$ sbt
[mongotest] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)

```
```

$ mongo
> use mongotest
> db.mongotest.users.find()
{ "_id" : ObjectId("5b39ecccf38fa02c055eda2f"), "className" : "models.User", "firstname" : "Paolo", "lastname" : "Rossi", "email" : "rossi@email.com" }
```
